"""Transaction inbound prop added

Revision ID: d21ea2362813
Revises: 5a04ec4d6dcd
Create Date: 2020-03-07 14:33:25.105219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21ea2362813'
down_revision = '5a04ec4d6dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('inbound', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'inbound')
    # ### end Alembic commands ###
