"""stock location table

Revision ID: d62598b9c47a
Revises: 36d055424772
Create Date: 2020-03-07 13:06:16.291704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62598b9c47a'
down_revision = '36d055424772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_location',
    sa.Column('stock_nr', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('stock_nr')
    )
    op.create_index(op.f('ix_stock_location_city'), 'stock_location', ['city'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_location_city'), table_name='stock_location')
    op.drop_table('stock_location')
    # ### end Alembic commands ###
